### ISSUE TITLE
Typora - update script doesn't work anymore

### ISSUE THREAD

**Issue by Jackenmen** [FranklinYu/chocolatey-packages#13]
AU updater errors on typora since last week (https://gist.github.com/FranklinYu/7d4536b29dacffbc807aaa67914180c6/c4b8dff404fc27093aa72447ed847426908a74d0)

**Comment by FranklinYu** [comment]
The feed https://www.typora.io/windows/dev_update.xml is broken. There is an invalid entity `&gr;` which should have been `&gt;`. I have to manually update and push all following versions until this page is fixed.

See typora/typora-issues#2743.

**Comment by FranklinYu** [comment]
Typora released a new version so this bug doesn’t matter any longer.
