### ISSUE TITLE
Do not create a folder in start menu for typora

### ISSUE THREAD

**Issue by aaronjheng** [FranklinYu/chocolatey-packages#9]
For now, typora is placed in a "(default)" folder in start menu. I think placing it in Start -> Programs directly will be better.

**Comment by FranklinYu** [comment]
This isn’t controlled in the package, but in the installer itself. You should file this issue at https://github.com/typora/typora-issues/.

If you know some installer argument that can change this behavior, please comment and I’ll re-open this issue.

**Comment by aaronjheng** [comment]
I tried to install it manually with the official installer. It turns out that there is a typora folder actually. But with choco, It becomes "(default)".

**Comment by FranklinYu** [comment]
I'm able to reproduce this behavior with https://typora.io/windows/typora-update-x64-0621.exe

So this should still be reported to the original author.

It's possibly that we can move the shortcut in installation script. I would research and do some experiment.
